# A sample Gemfile
source 'https://rubygems.org'

ruby '2.2.3'

gem 'rubocop', '0.68' # 2.2 系に対応しているラストバージョン
gem 'solargraph'
  gem 'nokogiri', '1.9.1' # 1.10 系を拾おうとすると ruby >=2.3.0 に引っかかって死亡
  gem 'parallel', '1.19.2' # 1.20 系を拾おうとすると ruby >= 2.4 に引っかかって死亡
