# A sample Gemfile
source 'https://rubygems.org'

ruby '2.7.2'

# code checker
gem 'rubocop'
gem "rubocop-rails"
gem "rubocop-rake"
gem "rubocop-rspec"
gem "rubocop-performance"
gem "haml_lint"
gem "standard"

# intellisense
gem 'solargraph'

# debug
gem 'debug'

# documentation
gem 'yard'
